using System.Text;
using Cobol2c.Runner.Jobs;
using Cobol2c.Runner.Triage.Models;

namespace Cobol2c.Runner.Reporting;

/// <summary>
/// Deterministic markdown bug report from structured TriageResult findings.
/// No LLM call — swap for ClaudeBugReportGenerator to add AI-generated narrative.
/// </summary>
public class TemplateBugReportGenerator : IBugReportGenerator
{
    public Task<string> GenerateAsync(TestJob job, TriageResult triage, CancellationToken ct)
    {
        var sb = new StringBuilder();

        sb.AppendLine("# Cobol2C Regression Bug Report");
        sb.AppendLine();
        sb.AppendLine($"**Job:** `{job.Id}`  ");
        sb.AppendLine($"**Suite:** {job.Suite}  ");
        sb.AppendLine($"**Machine:** {job.Machine}  ");
        sb.AppendLine($"**TCs:** {string.Join(", ", job.Tcs)}  ");
        sb.AppendLine($"**Generated:** {DateTime.UtcNow:u}  ");
        sb.AppendLine();

        if (!triage.HasRegressions)
        {
            sb.AppendLine("## Result: No regressions detected");
            sb.AppendLine();
            sb.AppendLine($"All {triage.ComparableCount} comparable TCs passed under Cobol2C.");
            if (triage.NotComparableCount > 0)
                sb.AppendLine($"_{triage.NotComparableCount} TC(s) were not comparable (also failed in reference — not a conversion regression)._");
            return Task.FromResult(sb.ToString());
        }

        sb.AppendLine($"## Summary");
        sb.AppendLine();
        sb.AppendLine($"**{triage.ComparableCount} regression(s)** detected " +
                      $"(failed Cobol2C, passed reference).");
        if (triage.NotComparableCount > 0)
            sb.AppendLine($"_{triage.NotComparableCount} TC(s) excluded — also failed in reference._");
        sb.AppendLine();
        sb.AppendLine("---");

        foreach (var f in triage.Findings)
        {
            sb.AppendLine();
            sb.AppendLine($"## TC {f.TC}");
            sb.AppendLine();
            sb.AppendLine("**Status:** Regression confirmed — passed reference, failed Cobol2C.");
            sb.AppendLine();

            if (f.Crash is { } crash)
            {
                sb.AppendLine("### Crash Signature");
                sb.AppendLine();
                sb.AppendLine($"- **SYS032 → MSG100 (smoking gun):** {crash.SmokingGun}");
                sb.AppendLine($"- **Missing EndTask (unclean shutdown):** {crash.HasMissingEndTask}");

                if (crash.CallChain is not null)
                    sb.AppendLine($"- **COBOL call chain:** `{crash.CallChain}`");

                if (crash.ActiveCsharpProgram is not null)
                    sb.AppendLine($"- **C# program active at crash:** `{crash.ActiveCsharpProgram}`");

                if (crash.DotNetStack.Length > 0)
                {
                    sb.AppendLine("- **.NET stack frames:**");
                    sb.AppendLine("  ```");
                    foreach (var frame in crash.DotNetStack)
                        sb.AppendLine($"  at {frame}(...)");
                    sb.AppendLine("  ```");
                }

                sb.AppendLine();
            }
            else
            {
                sb.AppendLine("_No CoreLog available for crash extraction (logging was off or log not found)._");
                sb.AppendLine();
            }

            if (f.FlowDivergence is { } div)
            {
                sb.AppendLine("### Flow Divergence");
                sb.AppendLine();
                sb.AppendLine($"- **Diverges at step:** {div.DivergenceIndex}");
                sb.AppendLine($"- **Failing path:** `{div.FailingStep}`");
                sb.AppendLine($"- **Reference path:** `{div.ReferenceStep}`");

                if (div.FailingContext.Length > 0)
                {
                    sb.AppendLine();
                    sb.AppendLine("**Failing flow context (±3 steps around divergence):**");
                    sb.AppendLine("```");
                    foreach (var step in div.FailingContext)
                        sb.AppendLine(step);
                    sb.AppendLine("```");
                }

                sb.AppendLine();
            }
        }

        sb.AppendLine("---");
        sb.AppendLine("_Generated by Cobol2c.Runner PoC — deterministic template mode._");
        sb.AppendLine("_Replace TemplateBugReportGenerator with ClaudeBugReportGenerator for AI narrative._");

        return Task.FromResult(sb.ToString());
    }
}
